### ISSUE TITLE
Example not work on Android

### ISSUE THREAD

**Issue by KingWu** [faithoflifedev/easy_onvif#17]
Tried to build with android. But, fail

```
No application found for TargetPlatform.android_arm64.
Is your project missing an android\AndroidManifest.xml?
Consider running "flutter create ." to create one.
```

**Comment by faithoflifedev** [comment]
HI @KingWu , 

This is not actually a problem with the code.  The `flutter_model` project in the example folder is minimal code that does not include the `android` target.  If you open the project on it's own and add the `android` target the code will run as expected.  I'll look at seeing if this can be made easier in the next release.
