### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by anhthoai** [faithoflifedev/easy_onvif#21]
Hello, when I build example, I see this error, could you please update example?
Because every version of flutter from sdk depends on collection 1.16.0 and xml >=6.2.0 depends on collection ^1.17.0, flutter from sdk is incompatible with xml >=6.2.0.
And because every version of easy_onvif from path depends on xml ^6.2.0, flutter from sdk is incompatible with easy_onvif from path.
So, because flutter_model depends on both easy_onvif from path and flutter from sdk, version solving failed.

**Comment by faithoflifedev** [comment]
I've updated the example pubspec.yaml to resolve the [issue](https://github.com/faithoflifedev/easy_onvif/commit/e120b081021a1ea321dca240e44d577c8a558cbc).

See the newly published [v2.0.13+9](https://pub.dev/packages/easy_onvif)
