### ISSUE TITLE
Package is not building (dependency problem)

### ISSUE THREAD

**Issue by DongsubShin** [faithoflifedev/easy_onvif#23]
Debug

Because every version of flutter from sdk depends on collection 1.16.0 and xml >=6.2.0 depends on collection ^1.17.0, flutter from sdk is incompatible with xml >=6.2.0.
And because easy_onvif >=2.0.13+11 depends on xml ^6.2.2, flutter from sdk is incompatible with easy_onvif >=2.0.13+11.
So, because cow depends on both flutter from sdk and easy_onvif ^2.0.13+13, version solving failed.
pub get failed (1; So, because cow depends on both flutter from sdk and easy_onvif ^2.0.13+13, version solving failed.)

Flutter version

Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (7 days ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0

**Comment by DongsubShin** [comment]
thank you for nice package 
easy_onvif is nice

**Comment by faithoflifedev** [comment]
@DongsubShin ,  the quick fix would be to add the following to your `pubspec.yaml`:

```yaml
dependency_overrides:
  collection: ^1.17.0
```

**Comment by DongsubShin** [comment]
> @DongsubShin , the quick fix would be to add the following to your `pubspec.yaml`:
> 
> ```yaml
> dependency_overrides:
>   collection: ^1.17.0
> ```

thanks!
