### ISSUE TITLE
 onvif.ptz.getStatus returns Unhandled Exception: NoSuchMethodError

### ISSUE THREAD

**Issue by DongsubShin** [faithoflifedev/easy_onvif#24]
I can get video streaming from rtsp
but i have problem controlling PTZ

log:

I/flutter (18523): [3;38;5;244m🐛 10:03:34.873035 DEBUG    UI Loggy - Ptz - getStatus
I/flutter (18523): [3;38;5;244m🐛 10:03:34.876047 DEBUG    UI Loggy - Onvif - URI: http://183.107.70.232/onvif/device_service
I/flutter (18523): [3;38;5;244m🐛 10:03:34.876153 DEBUG    UI Loggy - Onvif - REQUEST:
I/flutter (18523): <?xml version="1.0" encoding="UTF-8"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing"><s:Header><Security xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" s:mustUnderstand="1"><UsernameToken><Username>admin</Username><Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">PASSWORD</Password><Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">WMKHRoILuYjNlP2vxSE0uQ==</Nonce><Created xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2022-11-30T11:32:43.468033Z</Created></UsernameToken></Security></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSc
D/EGL_emulation(18523): app_time_stats: avg=16.71ms min=7.03ms max=25.91ms count=60
I/flutter (18523): [3;38;5;244m🐛 10:03:36.023021 DEBUG    UI Loggy - Onvif - RESPONSE:
I/flutter (18523): <?xml version="1.0" encoding="UTF-8"?>
I/flutter (18523): <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:axt="http://www.onvif.org/ver20/analytics" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:pt="http://www.onvif.org/ver10/pacs" xmlns:trt2="http://www.onvif.org/ver20/analytics/radiometry" xmlns:fc="http://www.onvif.org/ver20/analytics/humanface" xmlns:bd="http://www.onvif.org/ver20/analytics/humanbody" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-

error Log:
E/flutter (18523): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (18523): Receiver: null
E/flutter (18523): Tried calling: []("$")
E/flutter (18523): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (18523): #1      OnvifUtil.mappedToString
E/flutter (18523): #2      _$PtzStatusFromJson
E/flutter (18523): #3      new PtzStatus.fromJson
E/flutter (18523): #4      _$GetStatusResponseFromJson
E/flutter (18523): #5      new GetStatusResponse.fromJson
E/flutter (18523): #6      _$BodyFromJson
E/flutter (18523): #7      new Body.fromJson
E/flutter (18523): #8      _$EnvelopeFromJson
E/flutter (18523): #9      new Envelope.fromJson
E/flutter (18523): #10     new Envelope.fromXml
E/flutter (18523): #11     Soap.retrieveEnvelope
E/flutter (18523): <asynchronous suspension>
E/flutter (18523): #12     Ptz.getStatus
E/flutter (18523): <asynchronous suspension>
E/flutter (18523): #13     DashBoardController.initializeOnvif
E/flutter (18523): <asynchronous suspension>

last error code image
<img width="618" alt="스크린샷 2022-11-30 오전 11 38 57" src="https://user-images.githubusercontent.com/13095734/204694413-992396e6-7003-43d3-8bcc-90bfe31e1675.png">

**Comment by DongsubShin** [comment]
getstatus now working
please change code(lib/src/util/util.dart) like this

  static String mappedToString(Map<String, dynamic> value) =>
      value != null ? value['\$'] : null;

**Comment by faithoflifedev** [comment]
Hi @DongsubShin , I just published a new version of the package `v2.0.13+14` that should resolve the issue.  Please let me know if it works for you.  I made a slightly different change from the one you supplied.
