### ISSUE TITLE
getpresets not working

### ISSUE THREAD

**Issue by DongsubShin** [faithoflifedev/easy_onvif#27]
presets = await onvif.ptz.getPresets(profs[0].token);

_Exception (Exception: Error code: {Code: {Value: {$: SOAP-ENV:Sender}}, Reason: {Text: {@xml:lang: en, $: Method 'GetPresets' not implemented: method name or namespace not recognized}}})

**Comment by faithoflifedev** [comment]
Hi @DongsubShin, 

Does this work when you use another Onvif software package to list presets?  The error listed above is saying that your Onvif device is responding with a "not implemented/supported" to the API request.  Meaning that the device does not support "preset" capability.  

I've been learning through people's feedback that many manufacturers are very loose in following the official Onvif spec.  For instance, related to issue #26 that you submitted, some devices don't support `RelativeMove`, the software can work-around this by retrieving the current pan/tilt/zoom settings of the camera and then doing an `AbsoluteMove` for the additional amount specified by the user.

If you an find an open source package that works for your device then I might be able to look at the work-around used there and add that same functionality to the `easy_onvif` package.
