### ISSUE TITLE
Unhandled exception: type 'Null' is not a subtype of type 'String' calling Onvif.connect

### ISSUE THREAD

**Issue by LODYZ** [faithoflifedev/easy_onvif#28]
Hi, i am using the ^2.0.13+17 version but when i try to call the method Onvif.connect i get this error:

Unhandled exception:
type 'Null' is not a subtype of type 'String'
#0      OnvifUtil.mappedToString (package:easy_onvif/src/util/util.dart:142:68)
#1      _$TimeZoneFromJson (package:easy_onvif/src/model/time_zone.g.dart:10:21)
#2      new TimeZone.fromJson (package:easy_onvif/src/model/time_zone.dart:18:7)
#3      _$SystemDateAndTimeFromJson (package:easy_onvif/src/model/system_date_and_time.g.dart:17:22)
#4      new SystemDateAndTime.fromJson (package:easy_onvif/src/model/system_date_and_time.dart:43:7)
#5      _$GetSystemDateAndTimeResponseFromJson (package:easy_onvif/src/model/system_date_time_response.g.dart:12:25)
#6      new GetSystemDateAndTimeResponse.fromJson (package:easy_onvif/src/model/system_date_time_response.dart:18:7)
#7      _$BodyFromJson (package:easy_onvif/src/model/body.g.dart:43:42)
#8      new Body.fromJson (package:easy_onvif/src/model/body.dart:214:55)
#9      _$EnvelopeFromJson (package:easy_onvif/src/model/envelope.g.dart:10:18)
#10     new Envelope.fromJson (package:easy_onvif/src/model/envelope.dart:20:7)
#11     new Envelope.fromXml (package:easy_onvif/src/model/envelope.dart:23:16)
#12     Soap.retrieveEnvelope (package:easy_onvif/src/soap.dart:67:21)
<asynchronous suspension>
#13     DeviceManagement.getSystemDateAndTime (package:easy_onvif/src/device_management.dart:150:22)
<asynchronous suspension>
#14     Onvif.initialize (package:easy_onvif/src/onvif_base.dart:96:22)
<asynchronous suspension>
#15     Onvif.connect (package:easy_onvif/src/onvif_base.dart:87:5)
<asynchronous suspension>
#16     OnvifHelperCommand.initializeOnvif (package:easy_onvif/cmd/onvif_helper_command.dart:28:14)
<asynchronous suspension>
#17     OnvifGetDeviceInformationResponseDeviceManagementCommand.run (package:easy_onvif/cmd/onvif_device_management_command.dart:68:5)
<asynchronous suspension>
#18     CommandRunner.runCommand (package:args/command_runner.dart:209:13)

I am attaching the whole log in the hope that it will be useful for solving the problem.

 👻 23:37:45.306368 INFO     UI Loggy - Onvif - initializing ...
🐛 23:37:45.309145 DEBUG    UI Loggy - DeviceManagement - getSystemDateAndTime
🐛 23:37:45.323206 DEBUG    UI Loggy - Onvif - URI: http://192.168.0.25/onvif/device_service
🐛 23:37:45.323269 DEBUG    UI Loggy - Onvif - REQUEST:
<?xml version="1.0" encoding="UTF-8"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing"><s:Header/><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GetSystemDateAndTime xmlns="http://www.onvif.org/ver10/device/wsdl"/></s:Body></s:Envelope>
🐛 23:37:45.577436 DEBUG    UI Loggy - Onvif - RESPONSE:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:wsc="http://schemas.xmlsoap.org/ws/2005/02/sc" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:ns2="http://www.onvif.org/ver10/pacs" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:ns1="http://www.onvif.org/ver10/accesscontrol/wsdl" xmlns:ns3="http://www.onvif.org/ver10/actionengine/wsdl" xmlns:tad="http://www.onvif.org/ver10/analyticsdevice/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:trv="http://www.onvif.org/ver10/receiver/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:vifsvr="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding" xmlns:vifsvr10="http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding" xmlns:vifsvr2="http://www.onvif.org/ver10/events/wsdl/EventBinding" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:vifsvr3="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding" xmlns:vifsvr4="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding" xmlns:vifsvr5="http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding" xmlns:vifsvr6="http://www.onvif.org/ver10/events/wsdl/PullPointBinding" xmlns:vifsvr7="http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding" xmlns:vifsvr8="http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:vifsvr9="http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tns1="http://www.onvif.org/ver10/topics"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><tds:GetSystemDateAndTimeResponse><tds:SystemDateAndTime><tt:DateTimeType>NTP</tt:DateTimeType><tt:DaylightSavings>false</tt:DaylightSavings><tt:TimeZone><tt:TZ/></tt:TimeZone><tt:UTCDateTime><tt:Time><tt:Hour>22</tt:Hour><tt:Minute>37</tt:Minute><tt:Second>45</tt:Second></tt:Time><tt:Date><tt:Year>2022</tt:Year><tt:Month>12</tt:Month><tt:Day>26</tt:Day></tt:Date></tt:UTCDateTime><tt:LocalDateTime><tt:Time><tt:Hour>22</tt:Hour><tt:Minute>37</tt:Minute><tt:Second>45</tt:Second></tt:Time><tt:Date><tt:Year>2022</tt:Year><tt:Month>12</tt:Month><tt:Day>26</tt:Day></tt:Date></tt:LocalDateTime></tds:SystemDateAndTime></tds:GetSystemDateAndTimeResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

Any idea why I'm getting this? Thank you in advance

**Comment by faithoflifedev** [comment]
Hello @LODYZ ,

The latest version is now `easy_onvif: ^2.0.13+19`, please let me know if this resolves the problem above.

**Comment by LODYZ** [comment]
Hello @faithoflifedev,

I just tried with the latest version and I don't get the error anymore! Thank you.

Unfortunately I'm getting another error that seems to be related to: https://github.com/faithoflifedev/easy_onvif/issues/30
I wrote a comment there
