### ISSUE TITLE
[DioErrorType.other]: HttpException: Connection closed while receiving data

### ISSUE THREAD

**Issue by DongsubShin** [faithoflifedev/easy_onvif#29]
I'm great fan of your package.
I've used your package well until last week. 
but i don't know why it doesn't work suddenly
i've tested onvif functionality of my cameras with other app(like onvier)
it worked well with other app but only gets error when i use flutter package

<img width="553" alt="스크린샷 2023-01-01 오후 11 21 08" src="https://user-images.githubusercontent.com/13095734/210173831-298ebc1e-72d9-4217-91c4-ca4753b9ce1e.png">

**Comment by faithoflifedev** [comment]
https://github.com/faithoflifedev/easy_onvif/issues/32#issuecomment-1493346568
