### ISSUE TITLE
DioError Connection closed while receiving data

### ISSUE THREAD

**Issue by DongsubShin** [faithoflifedev/easy_onvif#30]
<img width="625" alt="스크린샷 2023-01-03 오전 11 16 29" src="https://user-images.githubusercontent.com/13095734/210292283-26ed1f0b-d87d-4540-9f87-9e1db14910ce.png">

always thank you about wonderful package

I've used this package very well
but since last week onvif.media.getProfile doesn't work suddenly

initialize, onvif.connect, everything worked well execpt get profile
what should i do?

Thank you in advance
* also is there any workaround to get profile token from cctv hardward directly?

**Comment by faithoflifedev** [comment]
Hello @DongsubShin,

Can you let me know which version of the package you are using?

Also, if you enable debugging, and provide the debug info, that could also provide a clue as to the problem.

```
final onvif = await Onvif.connect(
      host: config['host'],
      username: config['username'],
      password: config['password'],
      logOptions: const LogOptions(
        LogLevel.debug,
        stackTraceLevel: LogLevel.error,
      )); 
```

**"also is there any workaround to get profile token from cctv hardward directly?"** - I'm not aware of any method to do this.

Based on the error info that you've provided, it loos lie the device is having a problem responding to the request.  Having the debug log could help trace the issue.

**Comment by DongsubShin** [comment]
/flutter (14197): 🐛 00:52:10.542713 DEBUG    UI Loggy - Media - getProfiles
I/flutter (14197): 🐛 00:52:10.550331 DEBUG    UI Loggy - Onvif - URI: http://183.107.70.232:9440/onvif/device_service
I/flutter (14197): 🐛 00:52:10.550574 DEBUG    UI Loggy - Onvif - REQUEST:
I/flutter (14197): <?xml version="1.0" encoding="UTF-8"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing"><s:Header><Security xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" s:mustUnderstand="1"><UsernameToken><Username>admin</Username><Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">8LeatWstS9/fkkdL8lALcyyJeas=</Password><Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">8VTbbC7+J+2TWvgKMgUEHQ==</Nonce><Created xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2023-01-03T16:20:54.207102Z</Created></UsernameToken></Security></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSc

/flutter (14197): ‼️ 00:52:10.612952 ERROR    UI Loggy - Onvif - ERROR:
I/flutter (14197): DioError [DioErrorType.other]: HttpException: Connection closed while receiving data, uri = http://183.107.70.232:9440/onvif/device_service

I've tested camera with other onvif apps(like Onvier). and it works well on those apps.

Flutter (Channel stable, 3.3.9, on macOS 12.3.1 21E258 darwin-arm, locale ko-KR)
easy_onvif: ^2.0.13+7

Thanks :)

**Comment by DongsubShin** [comment]
/flutter (14197): 🐛 00:52:10.542713 DEBUG    UI Loggy - Media - getProfiles
I/flutter (14197): 🐛 00:52:10.550331 DEBUG    UI Loggy - Onvif - URI: http://183.107.70.232:9440/onvif/device_service
I/flutter (14197): 🐛 00:52:10.550574 DEBUG    UI Loggy - Onvif - REQUEST:
I/flutter (14197): <?xml version="1.0" encoding="UTF-8"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing"><s:Header><Security xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" s:mustUnderstand="1"><UsernameToken><Username>admin</Username><Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">8LeatWstS9/fkkdL8lALcyyJeas=</Password><Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">8VTbbC7+J+2TWvgKMgUEHQ==</Nonce><Created xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2023-01-03T16:20:54.207102Z</Created></UsernameToken></Security></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSc

/flutter (14197): ‼️ 00:52:10.612952 ERROR    UI Loggy - Onvif - ERROR:
I/flutter (14197): DioError [DioErrorType.other]: HttpException: Connection closed while receiving data, uri = http://183.107.70.232:9440/onvif/device_service

I've tested camera with other onvif apps(like Onvier). and it works well on those apps.

Flutter (Channel stable, 3.3.9, on macOS 12.3.1 21E258 darwin-arm, locale ko-KR)
easy_onvif: ^2.0.13+7

Thanks :)

**Comment by DongsubShin** [comment]
/flutter (14197): 🐛 00:52:10.542713 DEBUG    UI Loggy - Media - getProfiles
I/flutter (14197): 🐛 00:52:10.550331 DEBUG    UI Loggy - Onvif - URI: http://183.107.70.232:9440/onvif/device_service
I/flutter (14197): 🐛 00:52:10.550574 DEBUG    UI Loggy - Onvif - REQUEST:
I/flutter (14197): <?xml version="1.0" encoding="UTF-8"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing"><s:Header><Security xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" s:mustUnderstand="1"><UsernameToken><Username>admin</Username><Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">8LeatWstS9/fkkdL8lALcyyJeas=</Password><Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">8VTbbC7+J+2TWvgKMgUEHQ==</Nonce><Created xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2023-01-03T16:20:54.207102Z</Created></UsernameToken></Security></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSc

/flutter (14197): ‼️ 00:52:10.612952 ERROR    UI Loggy - Onvif - ERROR:
I/flutter (14197): DioError [DioErrorType.other]: HttpException: Connection closed while receiving data, uri = http://183.107.70.232:9440/onvif/device_service

I've tested camera with other onvif apps(like Onvier). and it works well on those apps.

Flutter (Channel stable, 3.3.9, on macOS 12.3.1 21E258 darwin-arm, locale ko-KR)
easy_onvif: ^2.0.13+7

Thanks :)

**Comment by faithoflifedev** [comment]
Hi @DongsubShin,

This looks like it might be a network related issue, but it's difficult to say with the limited information.

I recommend installing the `cli utility` with the command:

`dart pub global activate easy_onvif`

Further instructions are available in the README - [https://github.com/faithoflifedev/easy_onvif/tree/main/bin#readme](https://github.com/faithoflifedev/easy_onvif/tree/main/bin#readme) quick start section.

Then check to see if the results of the `onvif device-management get-services` command give the same IP address that you are using to connect to your Onvif device.  The results of the command will look something like:

```
[
  {
    "Namespace": "http://www.onvif.org/ver10/device/wsdl",
    "XAddr": "http://192.168.1.182/onvif/device_service",
    "Version": {
      "Major": 16,
      "Minor": 12
    },
    "Capabilities": null
  },
  ...
```

If the value for `"XAddr"` (in the section with `"Namespace": "http://www.onvif.org/ver10/device/wsdl"`) is different in terms of IP address, port or if it doesn't end in "/onvif/device_service" this could be the problem.

**Comment by LODYZ** [comment]
Hello, 

I am getting a similar error during Onvif.connect or calling (onvif device-management get-device-information --log-level debug). I hope that it can be useful. Thank you



👻 14:13:50.294820 INFO     UI Loggy - Onvif - initializing ...
🐛 14:13:50.297588 DEBUG    UI Loggy - DeviceManagement - getSystemDateAndTime
🐛 14:13:50.313086 DEBUG    UI Loggy - Onvif - URI: http://192.168.0.25/onvif/device_service
🐛 14:13:50.313162 DEBUG    UI Loggy - Onvif - REQUEST:
<?xml version="1.0" encoding="UTF-8"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing"><s:Header/><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GetSystemDateAndTime xmlns="http://www.onvif.org/ver10/device/wsdl"/></s:Body></s:Envelope>
🐛 14:13:50.555788 DEBUG    UI Loggy - Onvif - RESPONSE:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:wsc="http://schemas.xmlsoap.org/ws/2005/02/sc" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:ns2="http://www.onvif.org/ver10/pacs" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:ns1="http://www.onvif.org/ver10/accesscontrol/wsdl" xmlns:ns3="http://www.onvif.org/ver10/actionengine/wsdl" xmlns:tad="http://www.onvif.org/ver10/analyticsdevice/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:trv="http://www.onvif.org/ver10/receiver/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:vifsvr="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding" xmlns:vifsvr10="http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding" xmlns:vifsvr2="http://www.onvif.org/ver10/events/wsdl/EventBinding" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:vifsvr3="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding" xmlns:vifsvr4="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding" xmlns:vifsvr5="http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding" xmlns:vifsvr6="http://www.onvif.org/ver10/events/wsdl/PullPointBinding" xmlns:vifsvr7="http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding" xmlns:vifsvr8="http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:vifsvr9="http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tns1="http://www.onvif.org/ver10/topics"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><tds:GetSystemDateAndTimeResponse><tds:SystemDateAndTime><tt:DateTimeType>NTP</tt:DateTimeType><tt:DaylightSavings>false</tt:DaylightSavings><tt:TimeZone><tt:TZ/></tt:TimeZone><tt:UTCDateTime><tt:Time><tt:Hour>13</tt:Hour><tt:Minute>13</tt:Minute><tt:Second>50</tt:Second></tt:Time><tt:Date><tt:Year>2023</tt:Year><tt:Month>1</tt:Month><tt:Day>8</tt:Day></tt:Date></tt:UTCDateTime><tt:LocalDateTime><tt:Time><tt:Hour>13</tt:Hour><tt:Minute>13</tt:Minute><tt:Second>50</tt:Second></tt:Time><tt:Date><tt:Year>2023</tt:Year><tt:Month>1</tt:Month><tt:Day>8</tt:Day></tt:Date></tt:LocalDateTime></tds:SystemDateAndTime></tds:GetSystemDateAndTimeResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

🐛 14:13:51.353807 DEBUG    UI Loggy - DeviceManagement - getServices
🐛 14:13:51.359715 DEBUG    UI Loggy - Onvif - URI: http://192.168.0.25/onvif/device_service
🐛 14:13:51.359803 DEBUG    UI Loggy - Onvif - REQUEST:
<?xml version="1.0" encoding="UTF-8"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing"><s:Header><Security xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" s:mustUnderstand="1"><UsernameToken><Username>admin</Username><Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">QdmgYLPlVkBOTJG2iJtH6c58VkI=</Password><Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">MM8ww9A45bnJiu0lcqIMpg==</Nonce><Created xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2023-01-08T13:13:50.001088Z</Created></UsernameToken></Security></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GetServices xmlns="http://www.onvif.org/ver10/device/wsdl"><IncludeCapability>true</IncludeCapability></GetServices></s:Body></s:Envelope>
🐛 14:13:51.509302 DEBUG    UI Loggy - Onvif - RESPONSE:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:wsc="http://schemas.xmlsoap.org/ws/2005/02/sc" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:ns2="http://www.onvif.org/ver10/pacs" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:ns1="http://www.onvif.org/ver10/accesscontrol/wsdl" xmlns:ns3="http://www.onvif.org/ver10/actionengine/wsdl" xmlns:tad="http://www.onvif.org/ver10/analyticsdevice/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:trv="http://www.onvif.org/ver10/receiver/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:vifsvr="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding" xmlns:vifsvr10="http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding" xmlns:vifsvr2="http://www.onvif.org/ver10/events/wsdl/EventBinding" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:vifsvr3="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding" xmlns:vifsvr4="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding" xmlns:vifsvr5="http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding" xmlns:vifsvr6="http://www.onvif.org/ver10/events/wsdl/PullPointBinding" xmlns:vifsvr7="http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding" xmlns:vifsvr8="http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:vifsvr9="http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tns1="http://www.onvif.org/ver10/topics"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><tds:GetServicesResponse><tds:Service><tds:Namespace>http://www.onvif.org/ver10/device/wsdl</tds:Namespace><tds:XAddr>http://192.168.0.25:80/onvif/device_service</tds:XAddr><tds:Capabilities><tds:Capabilities><tds:Network NTP="3" HostnameFromDHCP="true" Dot11Configuration="true" DynDNS="false" IPVersion6="false" ZeroConfiguration="false" IPFilter="false"></tds:Network><tds:Security RELToken="false" HttpDigest="false" UsernameToken="true" KerberosToken="false" SAMLToken="false" X.509Token="false" RemoteUserHandling="false" Dot1X="false" DefaultAccessPolicy="false" AccessPolicyConfig="false" OnboardKeyGeneration="false" TLS1.2="true" TLS1.1="true" TLS1.0="false"></tds:Security><tds:System HttpSupportInformation="false" HttpSystemLogging="false" HttpSystemBackup="false" HttpFirmwareUpgrade="false" FirmwareUpgrade="true" SystemLogging="true" SystemBackup="false" RemoteDiscovery="false" DiscoveryBye="false" DiscoveryResolve="false"></tds:System></tds:Capabilities></tds:Capabilities><tds:Version><tt:Major>2</tt:Major><tt:Minor>50</tt:Minor></tds:Version></tds:Service><tds:Service><tds:Namespace>http://www.onvif.org/ver10/media/wsdl</tds:Namespace><tds:XAddr>http://192.168.0.25:80/onvif/device_service</tds:XAddr><tds:Capabilities><trt:Capabilities><trt:ProfileCapabilities MaximumNumberOfProfiles="3"></trt:ProfileCapabilities><trt:StreamingCapabilities RTP_RTSP_TCP="true" RTP_TCP="true" RTPMulticast="true"></trt:StreamingCapabilities></trt:Capabilities></tds:Capabilities><tds:Version><tt:Major>2</tt:Major><tt:Minor>50</tt:Minor></tds:Version></tds:Service><tds:Service><tds:Namespace>http://www.onvif.org/ver10/events/wsdl</tds:Namespace><tds:XAddr>http://192.168.0.25:80/onvif/device_service</tds:XAddr><tds:Capabilities><tev:Capabilities WSPausableSubscriptionManagerInterfaceSupport="false" WSPullPointSupport="true" WSSubscriptionPolicySupport="true"></tev:Capabilities></tds:Capabilities><tds:Version><tt:Major>2</tt:Major><tt:Minor>50</tt:Minor></tds:Version></tds:Service><tds:Service><tds:Namespace>http://www.onvif.org/ver20/imaging/wsdl</tds:Namespace><tds:XAddr>http://192.168.0.25:80/onvif/device_service</tds:XAddr><tds:Capabilities><timg:Capabilities></timg:Capabilities></tds:Capabilities><tds:Version><tt:Major>2</tt:Major><tt:Minor>50</tt:Minor></tds:Version></tds:Service><tds:Service><tds:Namespace>http://www.onvif.org/ver10/deviceIO/wsdl</tds:Namespace><tds:XAddr>http://192.168.0.25:80/onvif/device_service</tds:XAddr><tds:Capabilities><tmd:Capabilities></tmd:Capabilities></tds:Capabilities><tds:Version><tt:Major>2</tt:Major><tt:Minor>50</tt:Minor></tds:Version></tds:Service><tds:Service><tds:Namespace>http://www.onvif.org/ver20/analytics/wsdl</tds:Namespace><tds:XAddr>http://192.168.0.25:80/onvif/device_service</tds:XAddr><tds:Capabilities><tan:Capabilities><tan:Analytics><tan:RuleSupport>"false"</tan:RuleSupport><tan:AnalyticsModuleSupport>"true"</tan:AnalyticsModuleSupport></tan:Analytics></tan:Capabilities></tds:Capabilities><tds:Version><tt:Major>2</tt:Major><tt:Minor>50</tt:Minor></tds:Version></tds:Service><tds:Service><tds:Namespace>http://www.onvif.org/ver20/ptz/wsdl</tds:Namespace><tds:XAddr>http://192.168.0.25:80/onvif/device_service</tds:XAddr><tds:Capabilities><tptz:Capabilities></tptz:Capabilities></tds:Capabilities><tds:Version><tt:Major>2</tt:Major><tt:Minor>50</tt:Minor></tds:Version></tds:Service></tds:GetServicesResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

🐛 14:13:51.530899 DEBUG    UI Loggy - DeviceManagement - getCapabilities
🐛 14:13:51.531366 DEBUG    UI Loggy - Onvif - URI: http://192.168.0.25/onvif/device_service
🐛 14:13:51.531394 DEBUG    UI Loggy - Onvif - REQUEST:
<?xml version="1.0" encoding="UTF-8"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing"><s:Header/><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GetCapabilities xmlns="http://www.onvif.org/ver10/device/wsdl"><Category>All</Category></GetCapabilities></s:Body></s:Envelope>
‼️ 14:13:51.720128 ERROR    UI Loggy - Onvif - ERROR:
DioError [DioErrorType.other]: HttpException: Connection closed while receiving data, uri = http://192.168.0.25/onvif/device_service
Unhandled exception:
Exception: DioError [DioErrorType.other]: HttpException: Connection closed while receiving data, uri = http://192.168.0.25/onvif/device_service
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
#1      DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
#2      DioMixin.post (package:dio/src/dio_mixin.dart:97:12)
#3      Soap.send (package:easy_onvif/src/soap.dart:29:30)
#4      Soap.retrieveEnvelope (package:easy_onvif/src/soap.dart:59:37)
#5      DeviceManagement.getCapabilities (package:easy_onvif/src/device_management.dart:32:33)
#6      Onvif.initialize (package:easy_onvif/src/onvif_base.dart:124:51)
<asynchronous suspension>
#7      Onvif.connect (package:easy_onvif/src/onvif_base.dart:87:5)
<asynchronous suspension>
#8      OnvifHelperCommand.initializeOnvif (package:easy_onvif/cmd/onvif_helper_command.dart:28:14)
<asynchronous suspension>
#9      OnvifGetDeviceInformationResponseDeviceManagementCommand.run (package:easy_onvif/cmd/onvif_device_management_command.dart:68:5)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>

#0      Soap.send (package:easy_onvif/src/soap.dart:47:7)
<asynchronous suspension>
#1      Soap.retrieveEnvelope (package:easy_onvif/src/soap.dart:59:26)
<asynchronous suspension>
#2      DeviceManagement.getCapabilities (package:easy_onvif/src/device_management.dart:32:22)
<asynchronous suspension>
#3      Onvif.initialize (package:easy_onvif/src/onvif_base.dart:124:28)
<asynchronous suspension>
#4      Onvif.connect (package:easy_onvif/src/onvif_base.dart:87:5)
<asynchronous suspension>
#5      OnvifHelperCommand.initializeOnvif (package:easy_onvif/cmd/onvif_helper_command.dart:28:14)
<asynchronous suspension>
#6      OnvifGetDeviceInformationResponseDeviceManagementCommand.run (package:easy_onvif/cmd/onvif_device_management_command.dart:68:5)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>

**Comment by faithoflifedev** [comment]
@DongsubShin, @LODYZ, are you using "Onvif Rtsp Server for Android"?

If so, issue #3 covers the problem you're experiencing.

If not, I recommend testing if other Onvif libraries work with your device (preferably open source) and let me know which works, so I can look at how others have solved the problem.

The error you're seeing in this case is a network issue where the device is dropping the connection, at this point I think I could only offer additional help if I have access to a device that allows me to recreate the problem.

**Comment by LODYZ** [comment]
Hello @faithoflifedev, no i am not using "Onvif Rtsp Server for Android".

At the Moment i have only tried the camera with onvier (an app) and It works. I Will try other libraries and update you.


Thank you for all the support!

**Comment by faithoflifedev** [comment]
@LODYZ are you running your code in the Android emulator?  If so, this solution might help - https://learnflutter.co/flutter-connection-closed-while-receiving-data/

**Comment by LODYZ** [comment]
Hello @faithoflifedev, I'm glad to inform you that I was able to resolve the device connection problems.

I encountered 3 problems:

1. "DioError Connection closed while receiving data"  -> Solved using deviceManagement.getServices()
2. Envelope header null -> I edited envelope.dart and envelope.g.dart (I know I shouldn't do it manually)
2. Multicast null during getProfiles-> I edited audio_encoder (I know I shouldn't do it manually)

If you want I created a fork where you can see the changes.
https://github.com/LODYZ/easy_onvif

Sorry if maybe that's not entirely correct but I'm new to the world of dart and onvif.

**Comment by faithoflifedev** [comment]
Hi @LODYZ,

Thanks for this.  It's helped me identify a couple of bugs.  It looks like there's a `Media2` profile - https://www.onvif.org/ver20/media/wsdl/media.wsdl - supported by some cameras that I was unaware of, so the current code doesn't support it.  I'll work on adding support in the coming days.  

In digging in to this I found that all three of `DeviceManagement`, `Media` and `Media2` use a `GetServiceCapabilitiesResponse`, which returns three different `Capabilities` objects.  I'm currently only properly returning the `Capabilities` for `DeviceManagement`.  So I'll try to correct this as well.

**Comment by faithoflifedev** [comment]
Hi @LODYZ, as an fyi, after a major overhaul of the code base, I've been able to create a new release that includes Media2 support, and fixes a number of bugs that I found in the original code base.  I've published a pre-release version at [easy_onvif v2.1.0-dev.3](https://pub.dev/packages/easy_onvif/versions/2.1.0-dev.3), I'd appreciate any feedback that you could offer.

**Comment by LODYZ** [comment]
Hi @faithoflifedev , thank you so much for all the work you are doing. I'll try the new release as soon as possibile.

**Comment by faithoflifedev** [comment]
https://github.com/faithoflifedev/easy_onvif/issues/32#issuecomment-1493346568 also deals with this issue.
