### ISSUE TITLE
[2.1.0-dev11] error during onvif.getProfiles() device media1

### ISSUE THREAD

**Issue by LODYZ** [faithoflifedev/easy_onvif#35]
Hi,

i am getting: type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast

I've debugged the code and the problem is given by the Multicast field which is an empty map (ie. `{ ..., multicast:{}, ...}`). 

The exception fire in the generated code:

video_encoder_configuration.g.dart
```
      multiCast: json['Multicast'] == null
          ? null
          : MulticastConfiguration.fromJson(
              json['Multicast'] as Map<String, dynamic>),
```
The problem is also present in the stable release
Can you make it nullable? Thank you

**Comment by faithoflifedev** [comment]
Ok, it's taken me a bit of time to see the problem on this one.  Your device is setting the multicast parameter to an "empty map" which is not the same as being "null", which is breaking the code.  I've updated the code to cover this, but if your device return empty maps in other areas there still could be issues.  I've now publishes v2.1.0-dev.12

**Comment by LODYZ** [comment]
Hi, problem solved with the latest version. Thank You
