### ISSUE TITLE
Flutter example application cannot run successfully

### ISSUE THREAD

**Issue by Flynn2018** [faithoflifedev/easy_onvif#38]
https://github.com/faithoflifedev/easy_onvif/tree/main/example/flutter_model can't run as Flutter application directly, not have the android and iOS directories. Please improve the example to make it easier for everyone to get started.

**Comment by faithoflifedev** [comment]
@Flynn2018 , you didn't provide an error code or list which version of the package you are using.

I've made a few adjustments to - https://pub.dev/packages/yt/versions/2.2.0-dev.1 - so if this is the version you are using the problem will likely be resolved.

**Comment by Flynn2018** [comment]
> @Flynn2018 , you didn't provide an error code or list which version of the package you are using.
> 
> I've made a few adjustments to - https://pub.dev/packages/yt/versions/2.2.0-dev.1 - so if this is the version you are using the problem will likely be resolved.

No error code and using package 2.1.0-dev.15. I just meant this plugin's example project cannot be opened as Flutter application and run directly because it has no android and iOS directories under https://github.com/faithoflifedev/easy_onvif/tree/main/example/flutter_model. This may be a little not friendly to Flutter beginners.

By the way, your changes that use CachedNetworkImage is good as the previous NetworkImageWithRetry cannot display the image with the url returned by the method getSnapshotUri plus the authentication information.
