### ISSUE TITLE
Is it possible to check if Onvif connect failed?

### ISSUE THREAD

**Issue by DongsubShin** [faithoflifedev/easy_onvif#41]
Thank you for nice package

Is it possible to check if onvif initialize failed ?

I want my app to Navigator.pop or show message if onvif connection failed.

Thanks in advance!

**Comment by faithoflifedev** [comment]
@DongsubShin, [v2.1.1-dev.1](https://pub.dev/packages/easy_onvif/versions/2.1.1-dev.1)  has been released with this functionality.  Please let me know if it works for you.
