### ISSUE TITLE
MulticastProbe with Auth

### ISSUE THREAD

**Issue by nikitakubasov** [faithoflifedev/easy_onvif#44]
Since a recent update Axis cameras require a digest authentication header to access onvif/device_service.

Since the library currently doesn't support it, Axis devices can no longer be detected using the probe. 

A solution would be the option to supply a username / password when doing a MulticastProbe.

**Comment by faithoflifedev** [comment]
Hello @nikitakubasov, thanks for the feedback.

It's been a while since I looked at the spec, but I don't remember seeing an option to send authentication with the probe.  If you can supply a documented spec for this then I could take a look at implementing it.

**Comment by nikitakubasov** [comment]
Hi @faithoflifedev, thanks for the reply.

Apparently, the reason of the error is something else:

https://github.com/FalkTannhaeuser/python-onvif-zeep/issues/90

Axis cameras seem to have an security feature, which was recently enabled by default. Disabling it is a workaround.

**Comment by faithoflifedev** [comment]
@nikitakubasov , thanks for referencing the solution.
