### ISSUE TITLE
using CLI for testing causes a crash on onvif probe list-devices

### ISSUE THREAD

**Issue by cfsbhawkins** [faithoflifedev/easy_onvif#48]
Im testing this lib for implementation and plugged in a brand new amcrest camera to my network and I am getting the following error running the probe command from the terminal.

`onvif probe list-devices
Unhandled exception:
type 'Null' is not a subtype of type 'List<dynamic>' in type cast
#0      ProbeMatch._listFromJson (package:easy_onvif/src/model/probe/probe_match.dart:123:20)
#1      _$ProbeMatchFromJson (package:easy_onvif/src/model/probe/probe_match.g.dart:13:26)
#2      new ProbeMatch.fromJson (package:easy_onvif/src/model/probe/probe_match.dart:61:7)
#3      ProbeMatches._unbound (package:easy_onvif/src/model/probe/probe_matches.dart:31:24)
#4      _$ProbeMatchesFromJson (package:easy_onvif/src/model/probe/probe_matches.g.dart:10:34)
#5      new ProbeMatches.fromJson (package:easy_onvif/src/model/probe/probe_matches.dart:17:7)
#6      MulticastProbe.probe.<anonymous closure> (package:easy_onvif/src/multicast_probe.dart:124:32)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#11     _StreamController._add (dart:async/stream_controller.dart:658:7)
#12     _StreamController.add (dart:async/stream_controller.dart:606:5)
#13     new _RawDatagramSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:2535:33)
#14     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#18     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
`

**Comment by faithoflifedev** [comment]
Hi @cfsbhawkins ,

Could you please provide the output with `--logo-level all` added to the command line.  It looks like the response from the camera may not be following the standard.  If I can see the response, then I can adjust the code.
