### ISSUE TITLE
new specifications support--thermal interface

### ISSUE THREAD

**Issue by Virczz** [faithoflifedev/easy_onvif#50]
Hi,@faithoflifedev. I am debugging a thermal camera and need to connect my camera via onvif, will you provide thermal camera interface support soon? Grateful thanks!
the [thermal link](https://www.onvif.org/specs/srv/thermal/ONVIF-Thermal-Service-Spec.pdf)

**Comment by faithoflifedev** [comment]
Hi @Virczz,

I took a look at the thermal spec and it doesn't look like it would be too difficult to implement.  My problem is that I don't have a device available to test any new code against.  I've learned that the spec and actual device implementations can be very different.

**Comment by Virczz** [comment]
Thank you for your response. Yes, although we plan to implement standard interfaces, not having a device is indeed a big hassle. I'll implement it myself and when it's ready for release I'll submit it here.
