### ISSUE TITLE
How send audio stream to camera ?

### ISSUE THREAD

**Issue by alishe79** [faithoflifedev/easy_onvif#51]
I wanna send audio to unv or any vendor camera support play sound in camera.
easy_onvif support this ?
if yes, how can i stream audio to camera using easy_onvif ?

**Comment by faithoflifedev** [comment]
Hello @alishe79,

This library and Onvif in general does not have any direct support for sending audio to a device.

You can use `easy_onvif` to get the RTSP audio stream uri, then you'll have to find another library to send or receive audio  on that stream.  Here's some sample code in c-sharp that i was able to find - [how-to-send-audio-on-rtsp-backchannel](https://stackoverflow.com/questions/59465932/how-to-send-audio-on-rtsp-backchannel)

You might also be able to test sending an audio stream to the device with the command line tool - [ffmpeg](https://raspberrypi.stackexchange.com/questions/1466/live-audio-stream-using-ffmpeg)

**Comment by alishe79** [comment]
Thank you @faithoflifedev 

can i get the only audio by uint8list ?
i wanna run audio byte array in audio Tflite model.
how i can do this ?

**Comment by alishe79** [comment]
by default class, use mobile microphone .

```dart```
`try {
            // Create the classifier and required supporting objects
            classifier = AudioClassifier.createFromFileAndOptions(context, currentModel, options)
            tensorAudio = classifier.createInputTensorAudio()
            recorder = classifier.createAudioRecord()
            startAudioClassification()
        } catch (e: IllegalStateException) {
            listener.onError(
                "Audio Classifier failed to initialize. See error logs for details"
            )

            Log.e("AudioClassification", "TFLite failed to load with error: " + e.message)
        }`
        
        [tflite audio classification example](https://github.com/tensorflow/examples/tree/master/lite/examples/audio_classification/android)
