### ISSUE TITLE
Couldn't connect with Ezviz H8c camera

### ISSUE THREAD

**Issue by shahriarsaem** [faithoflifedev/easy_onvif#52]
Can any one tell me how to connect with Ezviz H8c camera?
I had write this method to connect with the camera
```
Future<void> connect({required String ip}) async {
    try {
      onvif = await Onvif.connect(
        host: ip,
        username: 'admin', // Replace with your username
        password: 'saem@123', // Replace with your password
      );

      log('💚 ✅🎄🍀🌲🐍 OnVIFService: connected to $ip');

      await getToken(); // Fetch token after successful connection
    } catch (error) {
      log('💚 ✅🎄🍀🌲🐍 OnVIFService: connection error: $error');
    }
  }
```
  here I called the method like this
```
  onLongPress: () async {
          await onvifService
              .connect(ip: '192.168.0.103:8000')
              .then((value) => onvifService.moveLeft());
        },
        child: const Text("PTZ"));
```
        
 What do I need to do for ptz control?

**Comment by faithoflifedev** [comment]
Hi @shahriarsaem ,

I recommend doing quick tests with the [cli](https://github.com/faithoflifedev/easy_onvif?tab=readme-ov-file#onvif-cli-onvif-at-the-command-prompt) feature to make sure that your device supports the functionality that you need.  Maybe after that try a couple of the Dart code examples (not using Flutter) since the coding is a little simpler.  After those steps you may find it easier to get things working in Flutter.

**Comment by shahriarsaem** [comment]
I tried this exception is showing
![image](https://github.com/faithoflifedev/easy_onvif/assets/31769751/69cbafc6-4b5c-44e5-8557-60aaec63db79)

**Comment by faithoflifedev** [comment]
@shahriarsaem,

You can get more detailed debug info with:
`onvif device-management get-device-information --log-level all`

But based on the error, it looks like you don't have the tool configured properly.  I suspect that the tool can't even find your device and is timing out even before attempting to authenticate to it.

Did you run `onvif authorize` to setup the config for the `cli` tool?  See the [REAMDE](https://github.com/faithoflifedev/easy_onvif/tree/main/bin#quick-start).

You can also run `onvif probe list-devices` to see what devices are advertising on your network.
