### ISSUE TITLE
HttpException: Invalid response line

### ISSUE THREAD

**Issue by wmhseir3** [faithoflifedev/easy_onvif#8]
hi, I tried the 0.0.13 with my physical nvt calling the onvif.ptz.moveLeft(profileToken). This will lead to the following exceptions:
E/flutter (20637): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: DioError [DioErrorType.other]: HttpException: Invalid response line, uri = http://192.168.1.103:2020/onvif/service
E/flutter (20637): #0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:821:20)
E/flutter (20637): #1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678:13)
E/flutter (20637): <asynchronous suspension>
E/flutter (20637): #2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)
E/flutter (20637): <asynchronous suspension>
E/flutter (20637): 
E/flutter (20637): #0      Soap.send (package:easy_onvif/src/soap.dart:34:7)
E/flutter (20637): <asynchronous suspension>
E/flutter (20637): #1      Soap.retrieveEnvlope (package:easy_onvif/src/soap.dart:43:26)
E/flutter (20637): <asynchronous suspension>
E/flutter (20637): #2      Ptz.continuousMove (package:easy_onvif/src/ptz.dart:30:5)
E/flutter (20637): <asynchronous suspension>
E/flutter (20637): #3      Ptz._move (package:easy_onvif/src/ptz.dart:103:5)
E/flutter (20637): <asynchronous suspension>
E/flutter (20637): #4      Ptz.moveLeft (package:easy_onvif/src/ptz.dart:120:5)

My sample codes are as followings:
    var onvif = Onvif(
        // host: '192.168.1.102:8000',
        host: '192.168.1.103:2020',
        username: '',
        password: '');
    //initiate connection
    await onvif.initialize();
    //get device info
    var deviceInfo = await onvif.deviceManagement.getDeviceInformation();
    var profileToken = 'profile_1';
    await onvif.ptz.moveLeft(profileToken);

please help to look into this issue next. The onvif server is only for your convenience to tackle the issue which is also applicable with my physical nvt too.

**Comment by faithoflifedev** [comment]
@wmhseir3, you may not actually be using v0.0.13

I was able to replicate a similar error and the relevant part is :
`Exception: Error code: {Code: {Value: {$: env:Sender}, Subcode: {Value: {$: ter:InvalidArgVal}, Subcode: {Value: {$: ter:NoProfile}}}}, Reason: {Text: {@xml:lang: en, $: The requested profile token ProfileToken does not exist.}}, Node: {$: http://www.w3.org/2003/05/soap-envelope/node/ultimateReceiver}, Role: {$: http://www.w3.org/2003/05/soap-envelope/role/ultimateReceiver}, Detail: {Text: {$: can not find this profile}}}`

The important part is at the end **{Text: {@xml:lang: en, $: The requested profile token ProfileToken does not exist.}}** which tells us that your profile token is invalid.

The profile token is case sensitive, I generated this error by changing my correct "Profile_1" token to incorrect "profile_1"

**Comment by wmhseir3** [comment]
hi, your assumption to replicate a similar error may be right in your end but not applicable with the issue in my case.
The profile token is correct as with case sensitive regarded but yield the "Unhandled Exception: Exception: DioError [DioErrorType.other]: HttpException: Invalid response line" issue using 0.0.13.

**Comment by faithoflifedev** [comment]
Hello @wmhseir3 , does v0.0.15 produce the same error?  The camera move logic was changed significantly recently.

**Comment by wmhseir3** [comment]
hi there,
I tried the 0.0.15 today and got different outcomes as followings. I think
there are some improvements as with 0.0.15 when testing using the same
codes as in the issue  #8.
I have one app called quadonvif pending to release to google app store
which I like to implement ptz features in it using easyonvif but no luck.
Please advise if you can provide valid soap for me to make this app work.
FYI, I attached the preview of this quadonvif page with ptz features in it.
William

E/flutter (14498): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled
Exception: Exception: DioError [DioErrorType.response]: Http status error
[400]
E/flutter (14498): Source stack:
E/flutter (14498): #0      DioMixin.fetch
(package:dio/src/dio_mixin.dart:473:35)
E/flutter (14498): #1      DioMixin.request
(package:dio/src/dio_mixin.dart:468:12)
E/flutter (14498): #2      DioMixin.post
(package:dio/src/dio_mixin.dart:91:12)
E/flutter (14498): #3      Soap.send
(package:easy_onvif/src/soap.dart:16:28)
E/flutter (14498): #4      Soap.retrieveEnvlope
(package:easy_onvif/src/soap.dart:42:37)
E/flutter (14498): #5      Ptz.relativeMove
(package:easy_onvif/src/ptz.dart:194:16)
E/flutter (14498): #6      Ptz.move (package:easy_onvif/src/ptz.dart:158:11)
E/flutter (14498): #7      Ptz.moveLeft
(package:easy_onvif/src/ptz.dart:171:11)
E/flutter (14498): #8      _MyHomePageState._initialize
(package:testeasyonvif/main.dart:88:21)


C Davis ***@***.***> 於 2022年2月17日 週四 上午7:56寫道：

**Comment by wmhseir3** [comment]
Hi,
I have just tried this 1.0.4 but can not get it through the pub get as
followings:
I realized my current issue is related to xml and therefore I do not wish
to solve  the pub get issues in the "dev_dependencies:".
Can you advise what should I do next before give it a real try? Thanks.

Because easy_onvif >=1.0.2 depends on xml ^5.4.1 which depends on
collection ^1.16.0, easy_onvif >=1.0.2 requires collection ^1.16.0.
And because every version of flutter from sdk depends on collection 1.15.0,
easy_onvif >=1.0.2 is incompatible with flutter from sdk.
So, because testeasyonvif depends on both flutter from sdk and easy_onvif
^1.0.4, version solving failed.
pub get failed (1; So, because testeasyonvif depends on both flutter from
sdk and easy_onvif ^1.0.4, version solving failed.)

William

wm3 hseir ***@***.***> 於 2022年5月10日 週二 上午9:23寫道：

**Comment by faithoflifedev** [comment]
@wmhseir3 
I've published v1.0.5 which among several other things backs out the dependencies that required overrides.

Let me know if this version solves the issues.

**Comment by wmhseir3** [comment]
hi, thanks for your reply and 1.0.5. here are the same results with logs
FYI.
i also attached the flutter doctor info hope they can help.

[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [版本
10.0.19042.1645], locale zh-TW)
[√] Android toolchain - develop for Android devices (Android SDK version
30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

compileSdkVersion 31

Launching lib\main.dart on CPH1941 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
W/FlutterActivityAndFragmentDelegate(28499): A splash screen was provided
to Flutter, but this is deprecated. See
flutter.dev/go/android-splash-migration for migration steps.
Debug service listening on ws://127.0.0.1:52884/ND883QZomr4=/ws
Syncing files to device CPH1941...
I/f.testeasyonvi(28499):
Thread[6,tid=28509,WaitingInMainSignalCatcherLoop,Thread*=0xb400007651c45000,peer=0x13500258,"Signal
Catcher"]: reacting to signal 3
I/f.testeasyonvi(28499):
I/f.testeasyonvi(28499): Wrote stack traces to tombstoned
I/flutter (28499): 2022-05-15T09:04:09.713293 I
_MyHomePageState._initialize: _MyHomePageState: _initialize:
I/flutter (28499): 2022-05-15T09:04:42.760269 I
_MyHomePageState._initialize: _MyHomePageState: _initialize:
deviceInfo.model = TL-IPC43AN-4
E/flutter (28499): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled
Exception: Exception: DioError [DioErrorType.response]: Http status error
[400]
E/flutter (28499): Source stack:
E/flutter (28499): #0      DioMixin.fetch
(package:dio/src/dio_mixin.dart:488:35)
E/flutter (28499): #1      DioMixin.request
(package:dio/src/dio_mixin.dart:483:12)
E/flutter (28499): #2      DioMixin.post
(package:dio/src/dio_mixin.dart:97:12)
E/flutter (28499): #3      Soap.send
(package:easy_onvif/src/soap.dart:15:28)
E/flutter (28499): #4      Soap.retrieveEnvlope
(package:easy_onvif/src/soap.dart:41:37)
E/flutter (28499): #5      Ptz.relativeMove
(package:easy_onvif/src/ptz.dart:202:16)
E/flutter (28499): #6      Ptz.move (package:easy_onvif/src/ptz.dart:166:11)
E/flutter (28499): #7      Ptz.moveLeft
(package:easy_onvif/src/ptz.dart:179:11)
E/flutter (28499): #8      _MyHomePageState._initialize
(package:testeasyonvif/main.dart:88:21)
E/flutter (28499): <asynchronous suspension>
E/flutter (28499):
E/flutter (28499): #0      Soap.send (package:easy_onvif/src/soap.dart:32:7)
E/flutter (28499): <asynchronous suspension>
E/flutter (28499): #1      Soap.retrieveEnvlope
(package:easy_onvif/src/soap.dart:41:26)
E/flutter (28499): <asynchronous suspension>
E/flutter (28499): #2      Ptz.relativeMove
(package:easy_onvif/src/ptz.dart:202:5)
E/flutter (28499): <asynchronous suspension>
E/flutter (28499): #3      Ptz.move (package:easy_onvif/src/ptz.dart:166:5)
E/flutter (28499): <asynchronous suspension>
E/flutter (28499): #4      Ptz.moveLeft
(package:easy_onvif/src/ptz.dart:179:5)
E/flutter (28499): <asynchronous suspension>
E/flutter (28499): #5      _MyHomePageState._initialize
(package:testeasyonvif/main.dart:88:5)
E/flutter (28499): <asynchronous suspension>


C Davis ***@***.***> 於 2022年5月15日 週日 上午12:26寫道：

**Comment by wmhseir3** [comment]
hi there,

i am thinking that we are getting nowhere as in past months. and i would
like to propose that if i can order the camera (as the link below) i am
using to your location.
so that you can debug and solve the issue easily. what do you think?
upon your consent, please get back to me with your delivery details.

TL-IPC43AN-4
<https://shopee.tw/product/751414054/16859438655?utm_source=an_16136160000&utm_medium=affiliates&utm_campaign=-&utm_content=527072397859414278526d39794c376a51534931----&af_siteid=an_16136160000&pid=affiliates&af_click_lookback=7d&af_viewthrough_lookback=1d&is_retargeting=true&af_reengagement_window=7d&af_sub_siteid=527072397859414278526d39794c376a51534931----&c=-&deep_and_deferred=1>

william

wm3 hseir ***@***.***> 於 2022年5月15日 週日 上午8:58寫道：

**Comment by faithoflifedev** [comment]
I've added my twitter handle to my GitHub profile, if you would like to PM me - twitter: [@faithoflifedev](https://twitter.com/faithoflifedev)

**Comment by faithoflifedev** [comment]
Hi @wmhseir3 , I've just published v1.0.9 which has been tested against 3 different Onvif devices.  A number of errors where found and corrected.  If you get a chance, try this new version.

**Comment by wmhseir3** [comment]
hi, I further removed the preset and replaced with the "await onvif.ptz
.moveLeft(profileToken); "
the program crashed as well with the following loggy information:
I/flutter ( 1911): 🐛 18:42:01.302422 DEBUG    UI Loggy - Ptz - moveLeft
I/flutter ( 1911): 🐛 18:42:01.307610 DEBUG    UI Loggy - Ptz - move
I/flutter ( 1911): 🐛 18:42:01.310837 DEBUG    UI Loggy - Ptz - relativeMove
I/flutter ( 1911): 🐛 18:42:01.321728 DEBUG    UI Loggy - Onvif - URI:
http://192.168.1.103:2020/onvif/service
I/flutter ( 1911): 🐛 18:42:01.322198 DEBUG    UI Loggy - Onvif - REQUEST:
I/flutter ( 1911): <?xml version="1.0" encoding="UTF-8"?><Envelope xmlns="
http://www.w3.org/2003/05/soap-envelope"><Header><Security xmlns:s="
http://www.w3.org/2003/05/soap-envelope" xmlns="
http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
s:mustUnderstand="1"><UsernameToken><Username>admin</Username><Password
Type="
http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">XVNpMcUseiUTEb5e0UgH2Xt/qYE=</Password><Nonce
EncodingType="
http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">LeizzzNkFZqWzrSo5nJX9g==</Nonce><Created
xmlns="
http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2022-05-28T10:41:59.249862Z</Created></UsernameToken></Security></Header><Body
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="
http://www.w3.org/2001/XMLSchema"><RelativeMove xmlns="
http://www.onvif.org/ver20/ptz
I/flutter ( 1911): ‼️ 18:42:01.440052 ERROR    UI Loggy - Onvif - ERROR:
I/flutter ( 1911): DioError [DioErrorType.response]: Http status error [400]
I/flutter ( 1911): #0      Loggy.log (package:loggy/src/loggy.dart:225:33)
I/flutter ( 1911): #1      Loggy.error (package:loggy/src/loggy.dart:266:7)
I/flutter ( 1911): #2      new Onvif.<anonymous closure>
(package:easy_onvif/src/onvif_base.dart:76:13)
I/flutter ( 1911): #3      _InterceptorWrapperMixin.onError
(package:dio/src/interceptor.dart:304:16)
I/flutter ( 1911): #4
 DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous
closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:574:28)
I/flutter ( 1911): #5      DioMixin.checkIfNeedEnqueue
(package:dio/src/dio_mixin.dart:789:22)
I/flutter ( 1911): #6
 DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous
closure> (package:dio/src/dio_mixin.dart:572:22)
I/flutter ( 1911): #7      new Future.<anonymous closure>
(dart:async/future.dart:252:37)
I/flutter ( 1911): #8      _rootRun (dart:async/zone.dart:1418:47)
I/flutter ( 1911): #9      _CustomZone.run (dart:async/zone.dart:1328:19)
I/flutter ( 1911): #10     _CustomZone.runGuarded
(dart:async/zone.dart:1236:7)
I/flutter ( 1911): #11     _CustomZone.bindCallbackGuarded.<anonymous
closure> (dart:async/zone.dart:1276:23)
I/flutter ( 1911): #12     _rootRun (dart:async/zone.dart:1426:13)
I/flutter ( 1911): #13     _CustomZ
E/flutter ( 1911): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled
Exception: Exception: DioError [DioErrorType.response]: Http status error
[400]
E/flutter ( 1911): Source stack:
E/flutter ( 1911): #0      DioMixin.fetch
(package:dio/src/dio_mixin.dart:488:35)
E/flutter ( 1911): #1      DioMixin.request
(package:dio/src/dio_mixin.dart:483:12)
E/flutter ( 1911): #2      DioMixin.post
(package:dio/src/dio_mixin.dart:97:12)
E/flutter ( 1911): #3      Soap.send
(package:easy_onvif/src/soap.dart:27:30)
E/flutter ( 1911): #4      Soap.retrieveEnvlope
(package:easy_onvif/src/soap.dart:56:37)
E/flutter ( 1911): #5      Ptz.relativeMove
(package:easy_onvif/src/ptz.dart:248:16)
E/flutter ( 1911): #6      Ptz.move (package:easy_onvif/src/ptz.dart:202:11)
E/flutter ( 1911): #7      Ptz.moveLeft
(package:easy_onvif/src/ptz.dart:219:11)
E/flutter ( 1911): #8      _MyHomePageState._initialize
(package:testeasyonvif/main.dart:115:21)
E/flutter ( 1911): <asynchronous suspension>
E/flutter ( 1911):
E/flutter ( 1911): #0      Soap.send (package:easy_onvif/src/soap.dart:44:7)
E/flutter ( 1911): <asynchronous suspension>
E/flutter ( 1911): #1      Soap.retrieveEnvlope
(package:easy_onvif/src/soap.dart:56:26)
E/flutter ( 1911): <asynchronous suspension>
E/flutter ( 1911): #2      Ptz.relativeMove
(package:easy_onvif/src/ptz.dart:248:5)
E/flutter ( 1911): <asynchronous suspension>
E/flutter ( 1911): #3      Ptz.move (package:easy_onvif/src/ptz.dart:202:5)
E/flutter ( 1911): <asynchronous suspension>
E/flutter ( 1911): #4      Ptz.moveLeft
(package:easy_onvif/src/ptz.dart:219:5)
E/flutter ( 1911): <asynchronous suspension>
E/flutter ( 1911): #5      _MyHomePageState._initialize
(package:testeasyonvif/main.dart:115:5)
E/flutter ( 1911): <asynchronous suspension>
E/flutter ( 1911):

William

wm3 hseir ***@***.***> 於 2022年5月28日 週六 下午6:25寫道：

**Comment by faithoflifedev** [comment]
@wmhseir3 , I assume you left out the part of the log that does the authentication to the camera.  If this isn't the case, then that's your problem.

If it's the case that authentication did occur properly, then it looks like the camera does not like the `Request` that the code is generating.  The only way I could troubleshoot this is by having access to the same model camera.

**Comment by wmhseir3** [comment]
hi, I did go through the Onvif.connect,
onvif.deviceManagement.getDeviceInformation()and onvif.media.getProfiles()
successfully.
And i was using the "profileToken = profiles[0].token;" to do the  getPresets
and movleft.

I tried to reach you through the twitter to get your private information
for camera arrangement but with no success.
can you advise further on this?
BTW, have you tried the onvif rtsp servers as in the following links? if
so, then you would not need to have  the same model camera from my end.
Let me know what you think.

https://www.happytimesoft.com/download.html

William


C Davis ***@***.***> 於 2022年5月30日 週一 上午3:48寫道：

**Comment by faithoflifedev** [comment]
@wmhseir3, it looks like twitter has receiving direct messages disabled by default.  Sorry about that.  I've enabled that now.

When I have some spare time, I'll try out the happytimesoft server as well.

**Comment by faithoflifedev** [comment]
@wmhseir3, v1.1.0 works with the [happytimesoft](https://www.happytimesoft.com) Onvif server

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-05-30 at 13 43 31](https://user-images.githubusercontent.com/923202/171040226-e3742ec2-1a2e-401c-a453-77681fadbd4d.png)

**Comment by wmhseir3** [comment]
hi, i tried 1.1.0 just now but with the same exception as of 1.0.9.
i'll contact you via twitter later on.
William

C Davis ***@***.***> 於 2022年5月31日 週二 上午1:45寫道：

**Comment by faithoflifedev** [comment]
Hello @wmhseir3 , I have some bad news for you.  I did extensive testing with `easy_onvif` and with a [node onvif](https://github.com/agsh/onvif) package, and neither package will perform a `RelativeMove` on a TL-IPC43AN-4 camera.  Strangely, `AbsoluteMove` works fine.  The error returned by the camera does not give any useful information towards any further resolution.

Here are the things you can try next:

- check with the manufacturer to  see if there is a firmware upgrade that resolves the issue
- you could try using the results of a ptz `GetStatus` to get the cameras current pan/tilt position, then use `AboluteMove` to simulate a `RelativeMove`
- switch to a different model or manufacturer.

**Comment by wmhseir3** [comment]
hi, i've just tried the 1.09 with my onvif device but with no luck.
I added some of the new lines as seen in your example however the program
crashed at the "var presets = await onvif.ptz.getPresets(profileToken);"
here listed the loggy output as followings:
I/flutter (31546): 🐛 18:31:09.749846 DEBUG    UI Loggy - Ptz - getPresets
I/flutter (31546): 🐛 18:31:09.761226 DEBUG    UI Loggy - Onvif - URI:
http://192.168.1.103:2020/onvif/service
I/flutter (31546): 🐛 18:31:09.761964 DEBUG    UI Loggy - Onvif - REQUEST:
I/flutter (31546): <?xml version="1.0" encoding="UTF-8"?><Envelope xmlns="
http://www.w3.org/2003/05/soap-envelope"><Header><Security xmlns:s="
http://www.w3.org/2003/05/soap-envelope" xmlns="
http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
s:mustUnderstand="1"><UsernameToken><Username>admin</Username><Password
Type="
http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">L3jVdKBs9fGbR3BOnrFdijVJUTo=</Password><Nonce
EncodingType="
http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">QX3727aPKtgs/UilvXrOLg==</Nonce><Created
xmlns="
http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2022-05-28T10:31:07.462321Z</Created></UsernameToken></Security></Header><Body
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="
http://www.w3.org/2001/XMLSchema"><GetPresets xmlns="
http://www.onvif.org/ver10/devic
I/flutter (31546): ‼️ 18:31:09.843851 ERROR    UI Loggy - Onvif - ERROR:
I/flutter (31546): DioError [DioErrorType.response]: Http status error [500]
I/flutter (31546): #0      Loggy.log (package:loggy/src/loggy.dart:225:33)
I/flutter (31546): #1      Loggy.error (package:loggy/src/loggy.dart:266:7)
I/flutter (31546): #2      new Onvif.<anonymous closure>
(package:easy_onvif/src/onvif_base.dart:76:13)
I/flutter (31546): #3      _InterceptorWrapperMixin.onError
(package:dio/src/interceptor.dart:304:16)
I/flutter (31546): #4
 DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous
closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:574:28)
I/flutter (31546): #5      DioMixin.checkIfNeedEnqueue
(package:dio/src/dio_mixin.dart:789:22)
I/flutter (31546): #6
 DioMixin.fetch._errorInterceptorWrapper.<anonymous closure>.<anonymous
closure> (package:dio/src/dio_mixin.dart:572:22)
I/flutter (31546): #7      new Future.<anonymous closure>
(dart:async/future.dart:252:37)
I/flutter (31546): #8      _rootRun (dart:async/zone.dart:1418:47)
I/flutter (31546): #9      _CustomZone.run (dart:async/zone.dart:1328:19)
I/flutter (31546): #10     _CustomZone.runGuarded
(dart:async/zone.dart:1236:7)
I/flutter (31546): #11     _CustomZone.bindCallbackGuarded.<anonymous
closure> (dart:async/zone.dart:1276:23)
I/flutter (31546): #12     _rootRun (dart:async/zone.dart:1426:13)
I/flutter (31546): #13     _CustomZ
E/flutter (31546): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled
Exception: Exception: Error code: {Code: {Value: {$: SOAP-ENV:Receiver},
Subcode: {Value: {$: ter:ActionNotSupported}}}}
E/flutter (31546): #0      Soap.send
(package:easy_onvif/src/soap.dart:40:11)
E/flutter (31546): <asynchronous suspension>
E/flutter (31546): #1      Soap.retrieveEnvlope
(package:easy_onvif/src/soap.dart:56:26)
E/flutter (31546): <asynchronous suspension>
E/flutter (31546): #2      Ptz.getPresets
(package:easy_onvif/src/ptz.dart:161:22)
E/flutter (31546): <asynchronous suspension>
E/flutter (31546): #3      _MyHomePageState._initialize
(package:testeasyonvif/main.dart:104:19)
E/flutter (31546): <asynchronous suspension>

William

C Davis ***@***.***> 於 2022年5月27日 週五 上午7:45寫道：

**Comment by wmhseir3** [comment]
hi there,
will get back to you on the results no later than this weekend.
william

C Davis ***@***.***> 於 2022年5月9日 週一 下午10:30寫道：

**Comment by faithoflifedev** [comment]
`I/flutter (31546): DioError [DioErrorType.response]: Http status error [500]`

The HTTP status code 500 is a generic error response. It means that the server encountered an unexpected condition that prevented it from fulfilling the request. This error is usually returned by the server when no other error code is suitable.

Essentially the device is not accepting the request.  Are you sure you've properly authenticated?
