### ISSUE TITLE
Can't build apk on example

### ISSUE THREAD

**Issue by anhthoai** [faithoflifedev/easy_onvif#9]
Hello. I can't run flutter build apk on example
Could you please guide me some?
"No file or variants found for asset: config.yaml"

**Comment by faithoflifedev** [comment]
@anhthoai , you need to provide your own assets/config.yaml file, with settings matching your Onvif compatible device.  You can view the sample file at - https://github.com/faithoflifedev/easy_onvif/blob/main/example/flutter_model/assets/config.sample.yaml

**Comment by anhthoai** [comment]
I have tried to add it and build successfully but don't see any result in app. Any missing?
![image](https://user-images.githubusercontent.com/5260500/154469828-5d069dd9-5f98-4f4c-adac-dc931c6488f9.png)
![image](https://user-images.githubusercontent.com/5260500/154469804-6849c2c6-130a-4c66-88f8-1c0c93a241aa.png)
![image](https://user-images.githubusercontent.com/5260500/154469928-aa120c74-5fca-4968-bcfc-25d30bf87ee6.png)
